In [ ]:
import pandas as pd
from pathlib import Path
import requests
import json

In [ ]:
def log_df(df, nrows=5):
    print(df.shape)
    return df.head(nrows)

In [ ]:
raw_data_paths = Path('../data').rglob('observations*.csv')
data_paths = [str(path) for path in raw_data_paths]
print(data_paths)

['../data/clarkstown-high-school-north/observations-200303.csv', '../data/cedar-creek-reserve/observations-199064.csv', '../data/los-angeles-bioblitz/observations-190446.csv', '../data/ciencia-ciudadana-peru-bats/observations-199065.csv', '../data/ciencia-ciudadana-peru-bees/observations-199066.csv']

# data modeling

In [27]:
path = Path(data_paths[0])
df = pd.read_csv(path)
log_df(df)

(1086, 42)

,id,observed_on_string,observed_on,time_observed_at,time_zone,user_id,user_login,created_at,updated_at,quality_grade,...,common_name,iconic_taxon_name,taxon_id,taxon_kingdom_name,taxon_phylum_name,taxon_class_name,taxon_order_name,taxon_family_name,taxon_genus_name,taxon_species_name
0,1551812,2015-05-27 08:30:00,2015-05-27,2015-05-27 05:30:00 -0700,Eastern Time (US & Canada),97128,lgertzer,2015-05-27 07:50:23 -0700,2019-05-12 16:17:45 -0700,research,...,Lettered Sphinx,Insecta,143452.0,Animalia,Arthropoda,Insecta,Lepidoptera,Sphingidae,Deidamia,Deidamia inscriptum
1,1556119,Thu May 28 2015 09:12:41 GMT-0400 (EDT),2015-05-28,2015-05-28 06:12:41 -0700,Eastern Time (US & Canada),105635,mcgovernm97,2015-05-28 06:14:24 -0700,2016-08-29 10:44:52 -0700,casual,...,maples,Plantae,47727.0,Plantae,Tracheophyta,Magnoliopsida,Sapindales,Sapindaceae,Acer,NaN
2,1556120,Thu May 28 2015 09:14:17 GMT-0400 (EDT),2015-05-28,2015-05-28 06:14:17 -0700,Eastern Time (US & Canada),105635,mcgovernm97,2015-05-28 06:14:43 -0700,2016-02-16 19:05:32 -0800,research,...,ribwort plantain,Plantae,53178.0,Plantae,Tracheophyta,Magnoliopsida,Lamiales,Plantaginaceae,Plantago,Plantago lanceolata
3,1556121,Thu May 28 2015 09:13:47 GMT-0400 (EDT),2015-05-28,2015-05-28 06:13:47 -0700,Eastern Time (US & Canada),105635,mcgovernm97,2015-05-28 06:14:25 -0700,2016-11-21 17:49:19 -0800,needs_id,...,Kentucky bluegrass,Plantae,60307.0,Plantae,Tracheophyta,Liliopsida,Poales,Poaceae,Poa,Poa pratensis
4,1556122,Thu May 28 2015 09:13:07 GMT-0400 (EDT),2015-05-28,2015-05-28 06:13:07 -0700,Eastern Time (US & Canada),105635,mcgovernm97,2015-05-28 06:14:25 -0700,2021-03-04 19:19:08 -0800,needs_id,...,dicots,Plantae,47124.0,Plantae,Tracheophyta,Magnoliopsida,NaN,NaN,NaN,NaN

In [77]:
df.columns

Index(['id', 'observed_on_string', 'observed_on', 'time_observed_at',
       'time_zone', 'user_id', 'user_login', 'created_at', 'updated_at',
       'quality_grade', 'license', 'url', 'image_url', 'sound_url', 'tag_list',
       'description', 'num_identification_agreements',
       'num_identification_disagreements', 'captive_cultivated',
       'oauth_application_id', 'place_guess', 'latitude', 'longitude',
       'positional_accuracy', 'public_positional_accuracy', 'geoprivacy',
       'taxon_geoprivacy', 'coordinates_obscured', 'positioning_method',
       'positioning_device', 'species_guess', 'scientific_name', 'common_name',
       'iconic_taxon_name', 'taxon_id', 'taxon_kingdom_name',
       'taxon_phylum_name', 'taxon_class_name', 'taxon_order_name',
       'taxon_family_name', 'taxon_genus_name', 'taxon_species_name'],
      dtype='object')

In [44]:
observations = [
    'id', 
    
    'time_observed_at',
    'user_id', 
    'quality_grade',  
    'url', 
    'image_url',  
    'latitude', 
    'longitude',
    'positional_accuracy', 
    'taxon_id'
]

inat_users = [
    'user_id', 
    'user_login', 
]

taxa_cols = [ 
    # 'species_guess',
    'scientific_name', 
    'common_name',
    'iconic_taxon_name', 
    'taxon_id', 
    'taxon_kingdom_name',
    'taxon_phylum_name',
    'taxon_class_name', 
    'taxon_order_name',
    'taxon_family_name', 
    'taxon_genus_name', 
    'taxon_species_name'
]

organizations = ["id", 'name']
projects = [
    "id",
    "organization_id",
    "title",
    "summary",
    "slug",
    "location",
    "start_date",
    "target_audience",
    "image",
    "description",
    "latitude",
    "longitude",
    "zoom",
    "contact",
]
project_links = ["id", "project_id", "url", "text"]

a project can have many data sources
- multi inat projects
- ebird
- environmental data